### ISSUE TITLE
Licensing and copyright

### ISSUE THREAD

**Issue by qmuntal** [golang-fips/openssl-fips#17]
Microsoft employees, including myself, are starting to push code into this repository, and probably other companies will join in the near future (e.g., Canonical).

It is fine for us to keep the MIT license but having Red Hat copyright here and there (e.g. [LICENSE](https://github.com/golang-fips/openssl-fips/blob/master/LICENSE#L3)) might cause confusion. I propose to avoid putting any copyright notice in the License file nor in the source code until we figure out (if necessary) the ownership of the code.

@derekparker @jaredpar

**Comment by derekparker** [comment]
This seems fine to me. @dbenoit17 thoughts?

**Comment by dbenoit17** [comment]
I'm fine with removing the Red Hat copyright notices, but it sounds like it's recommended to still have some kind of copyright notice.  What about something like `Copyright The Golang FIPS Authors`?

**Comment by qmuntal** [comment]
`Copyright The Golang FIPS Authors` seems like a good compromise. We have passed this proposal to our legal team and is also ok with that.

**Comment by dbenoit17** [comment]
@qmuntal change has been merged, are we all set to close this?

**Comment by qmuntal** [comment]
> @qmuntal change has been merged, are we all set to close this?

Just submitted #40, the only missing piece.
