### ISSUE TITLE
Missing symbols when building against OpenSSL v1.0.2

### ISSUE THREAD

**Issue by dbenoit17** [golang-fips/openssl-fips#21]
The new HKDF symbols to support TLSv1.3 are conditionally defined for openssl >= v1.1.1.  When building against older versions, for example in the ubi7 image, the symbols are still expected by the Go compiler but are undefined.  This causes builds to fail with older versions of openssl.

https://github.com/dbenoit17/openssl-fips/actions/runs/3159199626/jobs/5142133065#step:12:811

**Comment by ueno** [comment]
Although we could provide a fallback implementation of HKDF using HMAC for openssl 1.0.2, it would certainly be not FIPS compliant. Maybe we should instead provide a stub implementation that always panics, given that the openssl backed HKDF is sorely used by crypto/tls and TLS 1.3 is not properly supported system-wide on RHEL-7.

**Comment by simo5** [comment]
I suggest disabling TLS 1.3 conditionally on systems where 1.0.2 is found.
That way there is no attempt to use a protocol that will end up causing a panic.
